version: 2
jobs:
  build:
    docker:
    - image: manimaul/proxygen-builder:stretch
    steps:
    - checkout
    - run:
        name: Build
        command: |
          git submodule update --init --recursive
          mkdir build
          pushd build
          cmake ..
          make install
          popd
    - run:
        name: GTests
        command: ./build/tests/runUnitTests
    - run:
        name: Py Integration Tests
        command: |
          pushd tests/py_int_test
          apt-get -y install python3 python3-pip python3-pycurl
          pip3 install -r requirements.txt
          popd
          ./build/vial_example & python3 tests/py_int_test/int_test.py
