version: 2
jobs:
  build:
    docker:
    - image: manimaul/proxygen-builder:stretch
    steps:
    - checkout
    - run:
        name: Build
        command: |
          git submodule update --init --recursive
          mkdir build
          cd build
          cmake ..
          make install
    - run:
        name: GTests
        command: /opt/mct/bin/runUnitTests
    - run:
        name: Py Integration Tests
        command: |
          cd src/tests/py_int_test
          apt-get -y install python3 python3-pip python3-pycurl
          pip install -r requirements.txt
          /opt/mct/bin/marine_chart_tileserver
          python int_test.py
