version: 2
jobs:
  build:
    docker:
    - image: manimaul/proxygen-builder:stretch
    steps:
    - checkout
    - run:
        name: Build
        command: |
          git submodule update --init --recursive
          mkdir build
          cd build
          cmake ..
          make
    - run:
        name: GTests
        command: ./build/runUnitTests
    - run:
        name: Py Integration Tests
        command: |
          pushd src/tests/py_int_test
          apt-get -y install python3 python3-pip python3-pycurl
          pip3 install -r requirements.txt
          popd
          ./build/exampleServer & python3 src/tests/py_int_test/int_test.py
